name: Lucius
main: com.thorindev.Lucius
author: ThorinDev
version: 2.0.0
commands:
  hello:
    usage: /hello
    aliases: [hi,hey]
  fakesay:
    usage: /fakesay Player Message
    aliases: [sudo,fs]
  colorchat:
    usage: /colorchat Message
    aliases: [cc,colourchat]
  fw:
    usage: /fw
    aliases: [firework,launchme]
  vanish:
    usage: /vanish
    aliases: [v,disappear]