name: Lucius
main: com.thorindev.Lucius
author: ThorinDev
version: 1.1.0
commands:
  hello:
    usage: /hello
  hi:
    usage: /hi
  hey:
    usage: /hi
  fakesay:
    usage: /fakesay Player Message
  colorchat:
    usage: /colorchat Message
  cc:
    usage: /cc Message
  fw:
    usage: /fw
  vanish:
    usage: /vanish