name: Lucius
main: com.thorindev.Lucius
author: ThorinDev
version: 1.1.0
commands:
  hello:
    usage: /hello
    description: Find out!
  hi:
    usage: /hi
    description: Find out!
  hey:
    usage: /hi
    description: Find out!
  fakesay:
    usage: /fakesay Player Message
    description: Make other people talk, no we are not the CIA
  colorchat:
    usage: /colorchat Message
    description: Colours your chat!
  colourchat:
    usage: /colourchat Message
    description: Colours your chat!
  cc:
    usage: /cc Message
   