name: Lucius
main: com.thorindev.Lucius
author: ThorinDev
version: 1.0.1
commands:
  hello:
    usage: /hello
    description: Find out!
  fakesay:
    usage: /fakesay Player Message
    description: Make other people talk, no we are not the CIA