name: Lucius
main: com.thorindev.Lucius
author: ThorinDev
version: 1.1.2
commands:
  hello:
    usage: /hello
    aliases: [hi,hey]
  fakesay:
    usage: /fakesay Player Message
    aliases: [sudo,fs]
  colorchat:
    usage: /colorchat Message
    aliases: [cc,colourchat]
  fw:
    usage: /fw
  vanish:
    usage: /vanish
  lucius:
    usage: /lucius
    aliases: [lc]